### ISSUE TITLE
example下的sale运行 npm run dev 报错

### ISSUE THREAD

**Issue by ChrisGou** [ElemeFE/page-skeleton-webpack-plugin#19]
example下的sale运行 npm run dev 报错 😭 -> "[PSG] Cannot read property 'newPage' of null"
我什么也没改
![image](https://user-images.githubusercontent.com/20291282/42859173-ffa0e29c-8a84-11e8-8bad-d09d6bff936e.png)

**Comment by Jocs** [comment]
终端报什么错

**Comment by ChrisGou** [comment]
![image](https://user-images.githubusercontent.com/20291282/42920281-60dc23f0-8b48-11e8-9dba-7eb17deaa755.png)

**Comment by newtestaa** [comment]
同遇到这个问题

**Comment by Lizzy07** [comment]
我自己起的项目也是报这个错误
`[09:54:03] ⚠ ｢pswp｣:  TypeError: Cannot read property 'newPage' of null
    at Skeleton.newPage (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:34:37)
    at Skeleton.genHtml (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:64:29)
    at Promise.all.routes.map (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:244:19)
    at Array.map (<anonymous>)
    at Skeleton.renderRoutes (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:242:31)
    at SockJSConnection.<anonymous> (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/page-skeleton-webpack-plugin/src/server.js:144
:57)
    at emitOne (events.js:116:13)
    at SockJSConnection.emit (events.js:211:7)
    at Session.didMessage (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/sockjs/lib/transport.js:246:25)
    at WebSocketReceiver.didMessage (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/sockjs/lib/trans-websocket.js:104:39)
    at WebSocket.<anonymous> (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/sockjs/lib/trans-websocket.js:70:24)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.dispatchEvent (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/faye-websocket/lib/faye/websocket/api/event_target.
js:24:10)
    at WebSocket._receiveMessage (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/faye-websocket/lib/faye/websocket/api.js:142:10)
    at Hybi.<anonymous> (/Users/liyizhi557/Documents/projects/umc-ui/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)`

**Comment by Hideer** [comment]
@Jocs  你好，今天发现了您这个骨架屏的解决方案本想着先跑跑看看，但是干一上手就出现了问题，example跑不了，报错如下
`  throw new OptionsValidationError(validationErrors)
    ^

PageSkeletonOptionsValidationError: Invalid configuration object. page-skeleton-webpack-plugin has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'storagies'. These properties are valid:
   object { pathname?, staticDir?, routes?, port?, loading?, text?, image?, button?, svg?, pseudo?, device?, debug?, minify?, defer?, excludes?, remove?, hide?, grayBlock?, cookies?, headless?, cssUnit?, decimal?, logLevel?, logTime?, noInfo?, quiet? }`
经过一顿google发现应该是webpack更新的问题，但是通过更新webpack版本并没有好转，你有什么好的解决方案么

**Comment by sailei1** [comment]
storagies 把这个配置属性 删掉就可以运行了

**Comment by Mr-wang007s** [comment]
已解决：PageSkeletonOptionsValidationError，
方法：移除webpack.config.js文件  line 119
