### ISSUE TITLE
一直提示Cannot read property 'newPage' of null"

### ISSUE THREAD

**Issue by dawang0123** [ElemeFE/page-skeleton-webpack-plugin#20]
![Uploading image.png…]()

**Comment by dawang0123** [comment]
Your application is running here: http://localhost:8587
[12:18:01] ℹ ｢pswp｣: begin to generator skeleton screen
[12:18:01] ⚠ ｢pswp｣:  TypeError: Cannot read property 'newPage' of null
    at Skeleton.newPage (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:34:37)
    at Skeleton.genHtml (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:64:29)
    at Promise.all.routes.map (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:244:19)
    at Array.map (<anonymous>)
    at Skeleton.renderRoutes (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/page-skeleton-webpack-plugin/src/skeleton.js:242:31)
    at SockJSConnection.<anonymous> (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/page-skeleton-webpack-plugin/src/server.js:144:57)
    at emitOne (events.js:116:13)
    at SockJSConnection.emit (events.js:211:7)
    at Session.didMessage (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/sockjs/lib/transport.js:246:25)
    at WebSocketReceiver.didMessage (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/sockjs/lib/trans-websocket.js:104:39)
    at WebSocket.<anonymous> (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/sockjs/lib/trans-websocket.js:70:24)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.dispatchEvent (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at WebSocket._receiveMessage (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/faye-websocket/lib/faye/websocket/api.js:142:10)
    at Hybi.<anonymous> (/Users/wangqian/Documents/work/task/ztjy_task_medal/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)

**Comment by jayZOU** [comment]
@dawang0123 
npm install puppeteer 的时候会默认下载一个Chromium ，你应该是这步出错，实际上可以直接运行本地下载好的chrome，没必要再去下载一个

```javascript
//node_modules\page-skeleton-webpack-plugin\src\skeleton.js
//26行
this.browser = await puppeteer.launch({ headless })
//改成
this.browser = await puppeteer.launch({ headless, executablePath: 'you/chrome/path/chrome.exe' })
```

**Comment by czlin** [comment]
@jayZOU 
![image](https://user-images.githubusercontent.com/9177693/44777249-b4275000-abac-11e8-990c-97be844e3f7c.png)

还是会报Cannot read property 'newPage' of null

**Comment by Jmingzi** [comment]
我也遇到了同样的问题。

![image](https://user-images.githubusercontent.com/9743418/45661074-7c1d8800-bb2e-11e8-85df-c1f452d7e0a8.png)

**Comment by haruhihi** [comment]
同样的问题
在 examples/sale 下 npm run defv

**Comment by jayZOU** [comment]
`set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1&&npm install puppeteer`
可以用缺省的方式去安装`puppeteer`，这样就不会下载`chromeium`了，可以后面自己指定本地chrome路径

**Comment by dblate** [comment]
多执行几次 npm install puppeteer 直到成功，如果有可用的代理仓库，可以  npm install puppeteer --registry=xxxx 提升一下网络访问的成功率

**Comment by huzewei** [comment]
我也遇到这个问题。log后发现 this.browser = await puppeteer.launch({ headless }) 一直是null.多执行几次 npm install puppeteer(registry淘宝镜像) 直到成功。会有一个安装chromeium的过程。最后解决了问题。但是最后生成的样式有问题

**Comment by yangfan-coder** [comment]
cnpm  install puppeteer
