### ISSUE TITLE
vue-cli3创建的项目在生成骨架代码的时候报错

### ISSUE THREAD

**Issue by Ecareyu** [ElemeFE/page-skeleton-webpack-plugin#40]
vue-cli3创建的项目在生成骨架代码的时候报错,不知道怎么解决。

我执行的是yarn dev，没有任何报错,但是在生成骨架的时候，报错了，以下是报错信息
```
[19:07:29] i ｢pswp｣: write C:\Users\ecareyu\Projects\demo\js\vue3-spa\dist\index.html successfully in /
[19:07:36] i ｢pswp｣: begin to generator skeleton screen
[19:07:44] i ｢pswp｣: generator skeleton screen successfully
(node:14592) UnhandledPromiseRejectionWarning: Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:14592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)ith .catch(). (rejection id: 1)
(node:14592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Plugin configration

```javascript
const { SkeletonPlugin } = require('page-skeleton-webpack-plugin')
const path = require('path')

module.exports = {
  configureWebpack: {
    plugins: [
      // vue-cli3自带html-webpack-plugin，所以我这边没有引入
      // 骨架屏插件
      new SkeletonPlugin({
        pathname: path.resolve(__dirname, './shell'),
        staticDir: path.resolve(__dirname, './dist'),
        routes: ['/'],
        port: '7890'
      })
    ]
  }
}
```

### Versions

- Page Skeleton: 0.10.12
- Webpack:4.15.1
- html-webpack-plugin:3.2.0

**Comment by Ecareyu** [comment]
不好意思，解决了，问题出在我的操作系统，path里缺少了一个环境变量C:\Windows\System32
