### ISSUE TITLE
yarn install 之后报错了

### ISSUE THREAD

**Issue by zhengguorong** [ElemeFE/page-skeleton-webpack-plugin#44]
/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/zhengguorong/project/feature/page-skeleton-webpack-plugin/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/zhengguorong/project/feature/page-skeleton-webpack-plugin/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/zhengguorong/project/feature/page-skeleton-webpack-plugin/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by Rockergmail** [comment]
+1

**Comment by fengyun2** [comment]
+1

**Comment by Hideer** [comment]
+1

**Comment by LeoZeda** [comment]
> webpack-cli安装了3.1.1但是报另一个错误了...

报什么错误？

**Comment by chenjiecloud** [comment]
+1

**Comment by wushengwang** [comment]
+1

**Comment by qqsupper** [comment]
升级了webpack-cli后报错，请问怎么解决

/Users/user/plugin/skeleton/page-skeleton-webpack-plugin/examples/sale/node_modules/page-skeleton-webpack-plugin/src/skeletonPlugin.js:17
    throw new OptionsValidationError(validationErrors)

**Comment by katoto** [comment]
listen EADDRINUSE: address already in use :::8091 端口怎么修改，都是这个错误

**Comment by hmyjyghh** [comment]
> 升级了webpack-cli后报错，请问怎么解决
> 
> /Users/user/plugin/skeleton/page-skeleton-webpack-plugin/examples/sale/node_modules/page-skeleton-webpack-plugin/src/skeletonPlugin.js:17 throw new OptionsValidationError(validationErrors)

我没升级，直接run dev 就报这个错
