### ISSUE TITLE
npm run dev报错，依赖包总是有问题

### ISSUE THREAD

**Issue by wubing0324** [ElemeFE/page-skeleton-webpack-plugin#93]
### Description

[Description of the bug or feature]

提示我安装style-loader，我安装style-loader后，报以下错误：
`Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\node-work\page-skeleton-webpack-plugin\examples\sale\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)`
提示我安装webpack，当我安装了webpack，又提示我安装style-loader，大神能否给些指导，我的webpack版本是4.9.1，webpack-cli版本是3.3.0

**Comment by wubing0324** [comment]
现在examples目录外npm install，再进去npm install，然后npm run dev就好了

**Comment by wubing0324** [comment]
先在examples目录外npm install，再进去npm install，然后npm run dev就好了
